/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ies.eed.practicajunit;

public class App extends GameApp {
  

    public static void main(String[] args) {
       
       launch();
    }
}
